Upload a link to the GitHub job
ably/test-observability-action pull request #20
Opened 2023-12-14 17:43 UTC by lawrence-forooghian

Currently, the observability server UI links to the workflow run attempt that the upload corresponds to. This is fine in the case where the workflow only contains a single job, as it did in ably-cocoa. But in the case where there’s more than one job in a workflow (e.g. in the case of a matrix build), there’s no way to tell which job an upload corresponds to. So, include this information in the upload.

Resolves #18.

2023-12-14 18:18 UTC, lawrence-forooghian commented
@owenpearson or @VeskeR — I'll also need one of you to update the required checks in this repo’s settings (I don't have the permissions, I'm guessing maybe you do?)

2024-01-10 07:53 UTC, VeskeR requested changes
LGTM! Happy to merge after minor comments are resolved.

I don't have access to set the required checks either. Will probably need @owenpearson for that.

2024-01-10 07:53 UTC, VeskeR commented on .github/workflows/check.yml
> +        # `first-job` + the current job’s index within the matrix
```suggestion
        # offset for `first-job` (1) + the current job’s index within the matrix (strategy.job-index)
```

2024-01-10 14:52 UTC, lawrence-forooghian commented
OK, I need to rethink this approach. Turns out that the order in which the jobs are listed in the action YAML file don't necessarily match that in which they are returned from the API — see e.g. https://github.com/ably/test-observability-action/actions/runs/7476602315/job/20347351917?pr=20.

2024-01-10 17:57 UTC, VeskeR commented
> OK, I need to rethink this approach. Turns out that the order in which the jobs are listed in the action YAML file don't necessarily match that in which they are returned from the API — see e.g. https://github.com/ably/test-observability-action/actions/runs/7476602315/job/20347351917?pr=20.

Wow, that's unexpected. Yeah, [the API request](https://api.github.com/repos/ably/test-observability-action/actions/runs/7476602315/attempts/1/jobs) for the workflow mentioned has `first-job` as second element in the array.

I couldn't find any other way to get a unique identifier for a job either.

It seems that the next best thing is to find the correct job in the API response by its name. There is a `github.job` prop for that, but it does not include matrix information, whereas in API response `name` prop is shown as `[job name] ([matrix.prop1], [matrix.prop2], ...)`.
Technically, we can concatenate the correct job name with matrix values (unless order of matrix properties is also not guaranteed) and expose it via JOB_NAME (instead of JOB_INDEX) and pass it to the action. It's not that far fetched from index calculation that we currently do with offsets and stuff.

@lawrence-forooghian WDYT?

2024-01-22 17:46 UTC, lawrence-forooghian commented
@VeskeR I've implemented your suggestion of using the job’s `name`. Would you be able to take another look, please?

2024-01-24 13:11 UTC, VeskeR approved these changes
LGTM

2024-01-24 14:04 UTC, merged